micronaut:
    application:
        name: ms1
datasources:
    default:
        url: jdbc:postgresql://localhost:5432/somedb
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
